In [51]:
import numpy as np 
from sklearn.datasets import load_diabetes 

In [52]:
# Loads diabetes dataset and directly separates features (x) and target (y)
x,y = load_diabetes(return_X_y= True)

In [53]:
x

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]], shape=(442, 10))

In [54]:
x.shape

(442, 10)

In [56]:
y

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [57]:
y.shape

(442,)

### Using Sklearn's Linear Regression 

In [9]:
from sklearn.model_selection import train_test_split 
x_train , x_test ,y_train , y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [11]:
print(x_train.shape)
print(x_test.shape)

(353, 10)
(89, 10)


In [12]:
from sklearn.linear_model import LinearRegression

reg = LinearRegression()

reg.fit(x_train,y_train)

y_pred = reg.predict(x_test)

In [13]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.45260276297191937

In [14]:
# m 
reg.coef_

array([  37.90402135, -241.96436231,  542.42875852,  347.70384391,
       -931.48884588,  518.06227698,  163.41998299,  275.31790158,
        736.1988589 ,   48.67065743])

In [15]:
# b 
reg.intercept_

np.float64(151.34560453985995)

### Making our own Linear Regression Class

In [78]:
class MeraLR : 

    def __init__(self):
        self.coef_ = None
        self.int_ = None 

    def fit(self,x_train,y_train):
        
        x_train = np.insert(x_train,0,1,axis=1)       # Note : A 

        # To calculate coeff 
        betas = np.linalg.inv(np.dot(x_train.T,x_train)).dot(x_train.T).dot(y_train)    # Note : B
        self.int_ = betas[0]
        self.coef_ = betas[1:]

    def predict(self,x_test): 
        y_pred = np.dot(x_test,self.coef_) + self.int_      # Note : C
        return y_pred
        

# Notes 
## A ) Why We Add a Column of 1s in Linear Regression

The linear regression equation is:

y = b₀ + b₁X₁ + b₂X₂ + ... + bₙXₙ

By inserting a column of 1s into `X_train`, we convert the intercept term (`b₀`) into a coefficient so it can be calculated using matrix multiplication through the Normal Equation.

```python
X_train = np.insert(X_train, 0, 1, axis=1)
```
https://numpy.org/doc/stable/reference/generated/numpy.insert.html

### Why This Is Necessary

- **Mathematical Integration:**  
  The intercept (`b₀`) is a constant. Multiplying it by 1 allows it to behave like a normal coefficient inside matrix operations.

- **Vectorized Calculation:**  
  This allows the Normal Equation:  

  `(XᵀX)⁻¹XᵀY`    to calculate both intercept and slope coefficients together in one operation.

- **Avoiding Origin Bias:**  
  Without this column, the regression line would be forced to pass through `(0,0)`, which can produce inaccurate predictions.

## B ) 

$Beta(\beta) = (X^T X)^{-1} X^T y$

## C ) The prediction equation is:

ŷ = Xβ + b

Where:

- `np.dot(x_test, self.coef_)` → Weighted sum of input features
- `self.int_` → Intercept / Bias term
- `y_pred` → Final prediction values generated by the model


In [64]:
# Call  our func 
lr = MeraLR()

In [65]:
lr.fit(x_train,y_train)

In [71]:
# Showing that we added the Ones Col in our data 
print('Og dataset shape : ',x_train.shape)
print('After adding Ones col:',np.insert(x_train,0,1,axis=1).shape)

Og dataset shape :  (353, 10)
After adding Ones col: (353, 11)


In [72]:
# since our model is ready . Lets Check teh accuracy  
y_pred = lr.predict(x_test)

In [73]:
# Accuarcy of Our own model (MeraLR)
r2_score(y_test,y_pred)

0.4526027629719195

In [74]:
# m
lr.coef_

array([  37.90402135, -241.96436231,  542.42875852,  347.70384391,
       -931.48884588,  518.06227698,  163.41998299,  275.31790158,
        736.1988589 ,   48.67065743])

In [75]:
# b 
lr.int_

np.float64(151.34560453985995)

In [77]:
# We are getting same results as the SKlearn class ,just by building our own model . 